version: ${project.version}
name: DeathUtils
main: com.danikvitek.deathutils.Main
api-version: 1.17

author: Danik Vitek
description: The plugin for controlling some death components of players and entities
commands:
  suicide:
    aliases: [killme]
    description: kills you (survival/adventure)
    usage: "/suicide"
  remember:
    aliases: [death, deathloc]
    description: tells you your last death location
    usage: "/remember"
  damage:
    aliases: [harm]
    description: deals certain damage to the specific entity
    usage: "/damage <target> <amount> [has_source]"